stdstar correct sky and flat fiber; scale ivar
desihub/desispec pull request #1817
Opened 2022-08-03 22:07 UTC by sbailey

This PR fixes #1810 for standard star fitting:
  * use the correct fiber when applying the fiberflat and sky subtraction
  * when scaling the flux by the fiberflat, also scale the ivar to match

Testing on all exposures of 20210531, this results in a distinct improvement in the scatter of the data-model G-R colors:
![image](https://user-images.githubusercontent.com/218471/182720221-8766791b-5dad-4d28-95f7-3ded73110917.png)

The test outputs are in `/global/cfs/cdirs/desi/users/sjbailey/spectro/redux/stdstar`, which used guadalupe inputs and re-ran just the stdstar fitting step for each tile.

2022-08-04 00:21 UTC, julienguy requested changes
Thank you for the bug fix. It does indeed improve the fit of standard stars.
I see the original code and this new version are missing the transformation to convert fiberflat wavelength from the Kitt Peak frame to the solar system barycenter. It is included in the routine ```fiberflat.apply_fiberflat(frame, fiberflat)```. It would be better to use directly this function here.

2022-08-04 23:03 UTC, sbailey commented
I updated to use `apply_fiberflat` and `subtract_sky`, which led to other changes for SkyModel object slicing and updating the tests and fixing a bug in fiberbitmasking when working on a sliced subset of a full frame, but in the end the improvements are similar:
![image](https://user-images.githubusercontent.com/218471/182969606-a21efda5-6d7a-41b6-87cc-fd6519925a71.png)

2022-08-05 16:56 UTC, sbailey commented
For the record: the reason why the results are different when using `apply_fiberflat` and `subtract_sky` is that those also propagate the error model from the fiberflat and sky models, which was previously ignored when doing `flux/fiberflat - sky` and `ivar*fiberflat**2`.

2022-08-05 22:12 UTC, julienguy approved these changes
Great. I checked the code and successfully ran std star fit for one tile and got slightly reduced rms.

2022-08-05 22:12 UTC, merged