Replace hard-coded paths with environment variables
desihub/desispec pull request #2294
Opened 2024-07-16 19:48 UTC by weaverba137

This PR fixes #2272.

2024-07-16 20:36 UTC, sbailey commented
To emphasize the WIP status as a warning to my future self: this requires updates to desimodules to define $DESI_TILES before it will work, and there are other places that also reference trunk that have not yet been updated (e.g. desispec.io.fibermap.assemble_fibermap).  But in the spirit of WIP, the basic structure of `get_readonly_filepath(os.environ['DESI_BLATFOO'])` shown here looks good.

2024-07-16 23:26 UTC, weaverba137 commented
@sbailey, while working on this, I noticed that fiberassign file names are specified in multiple ways *e.g.* `f'{tileid // 1000:03d}` versus `stileid = f'{tileid:06d}'; ... stileid[:3] ...`. Should we define a function instead and only ever use the function to find the fiberassign file?

2024-07-17 17:05 UTC, sbailey commented
> @sbailey, while working on this, I noticed that fiberassign file names are specified in multiple ways e.g. f'{tileid // 1000:03d} versus stileid = f'{tileid:06d}'; ... stileid[:3] .... Should we define a function instead and only ever use the function to find the fiberassign file?

Good point.  Best would be to add a new filetype entry to `desispec.io.findfile`, e.g. "fiberassignsvn", which would then do this $DESI_TILE+tileid etc. wrangling to report the canonical name of a fiberassign file in svn.  This would augment the pre-existing filetype='fiberassign' which reports where the fiberassign file is in the raw data stream.

2024-07-17 19:56 UTC, weaverba137 commented
OK, and while working on `findfile`, I found this. This can't be right can it (around line 294)?
```python
    if isinstance(tile, str):    tile = int(night)
```

2024-07-17 20:10 UTC, sbailey commented
Indeed, that whole block was introduced (by me!) in PR #1931 and is a cut-and-paste typo on multiple lines:
```python
    #- be robust to str vs. int
    if isinstance(healpix, str): healpix = int(healpix)
    if isinstance(night, str):   night = int(night)
    if isinstance(expid, str):   expid = int(night)
    if isinstance(tile, str):    tile = int(night)
    if isinstance(spectrograph, str): spectrogrpah = int(night)
```
Note the "spectrogrpah" typo as well.

@weaverba137 would you like me to fix these in a separate PR (with tests!) or will you fix it in your current branch?

2024-07-17 20:22 UTC, weaverba137 commented
I will do a minimal fix on this branch, but let's think about a separate PR to do more robust unit tests on `findfile`.

In addition, I think a future policy for all PRs should be "if you are trying to create a file name, you **must** use `findfile`".

2024-07-17 21:02 UTC, weaverba137 commented
I'm moving this out of draft status.

@sbailey, please review [this listing of 'trunk' occurrences](https://github.com/search?q=repo%3Adesihub%2Fdesispec+trunk+NOT+trunk_py+NOT+language%3A%22Jupyter+Notebook%22+NOT+path%3Adoc&type=code). I believe these files can be ignored:

1. etc/cron_dailytest.sh
2. etc/desi_nersc_pipetest.py
3. py/desispec/database/redshift.py (the entire database directory is deprecated anyway)
4. py/desispec/test/test_photo.py
5. py/desispec/test/integration_test.py

I'm not sure about these, because a URL is being constructed instead of a filename:

6. py/desispec/scripts/procdashboard.py
7. py/desispec/scripts/zprocdashboard.py

These files have been updated:

8. py/desispec/io/photo.py
9. bin/desi_tile_qa_reference
10. py/desispec/io/fibermap.py
11. py/desispec/workflow/exptable.py
12. py/desispec/scripts/archive_night.py

2024-07-17 21:04 UTC, weaverba137 commented on py/desispec/io/fibermap.py
> +        if 'DESI_TILES' in os.environ:
Technically, this violates our proposed rule of 'if `DESI_TILES` is not defined, fail', so I can make this stricter if necessary.

2024-07-18 11:55 UTC, akremin commented
The procdashboards are used frequently and so a refactor is welcome, but I
also think it is okay to leave as-is since it is a special case where it
constructs a url. If you want, you are welcome to update the logic so that
it uses findfile for the relative path and then creates the url based on
that. But I'm also fine with leaving it. These files aren't moving anytime
soon, so keeping the dashboard code as-is is very low risk.

On Wed, Jul 17, 2024, 11:02 PM Benjamin Alan Weaver <
***@***.***> wrote:

> I'm moving this out of draft status.
>
> @sbailey <https://github.com/sbailey>, please review this listing of
> 'trunk' occurrences
> <https://github.com/search?q=repo%3Adesihub%2Fdesispec+trunk+NOT+trunk_py+NOT+language%3A%22Jupyter+Notebook%22+NOT+path%3Adoc&type=code>.
> I believe these files can be ignored:
>
>    1. etc/cron_dailytest.sh
>    2. etc/desi_nersc_pipetest.py
>    3. py/desispec/database/redshift.py (the entire database directory is
>    deprecated anyway)
>    4. py/desispec/test/test_photo.py
>    5. py/desispec/test/integration_test.py
>
> I'm not sure about these, because a URL is being constructed instead of a
> filename:
>
>    6. py/desispec/scripts/procdashboard.py
>    7. py/desispec/scripts/zprocdashboard.py
>
> These files have been updated:
>
>    8. py/desispec/io/photo.py
>    9. bin/desi_tile_qa_reference
>    10. py/desispec/io/fibermap.py
>    11. py/desispec/workflow/exptable.py
>    12. py/desispec/scripts/archive_night.py
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/desihub/desispec/pull/2294#issuecomment-2234280565>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBM5O3O4F43RPC3ZGOVJETZM3LXPAVCNFSM6AAAAABK7HYDRGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMZUGI4DANJWGU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-07-19 16:33 UTC, sbailey requested changes

2024-07-19 16:41 UTC, weaverba137 commented on py/desispec/workflow/exptable.py
> +            if svn_exists:
Ah, you're just making a comment here, not actually requesting changes?

2024-07-19 16:41 UTC, weaverba137 commented on py/desispec/workflow/exptable.py
> +                                          tile=tileid, return_exists=True)
Done.

2024-07-19 16:42 UTC, weaverba137 commented on py/desispec/io/photo.py
> +                                     tile=tileid, readonly=True, return_exists=True)
I think what you're saying is to just remove the `tiles_dir` argument. Is that correct?

2024-07-19 16:49 UTC, weaverba137 commented
I can't add comments directly to this line item:

> Thanks for noting that. Seeing that you've added a tiles_dir option to findfile, this code could intercept missing $DESI_TILES and fall back to doing what it would have done before, i.e. using tiles_dir=$DESI_TARGET/fiberassign/tiles/trunk instead (while still printing a warning).

I'm not entirely sure what you're recommending here. Maybe you could express this as a code snippet?

However, I now realize that the way `findfile` is modified in this branch, an exception will be thrown if `FIBER_ASSIGN_DIR` is not defined *anyway*, and so maybe the solution is to catch a potential `KeyError` thrown by findfile, add a helpful message, and re-raise.

2024-07-19 17:10 UTC, sbailey commented on py/desispec/workflow/exptable.py
> +            if svn_exists:
yes, this was just for the record in the PR; no change needed here.

2024-07-19 17:11 UTC, sbailey commented on py/desispec/io/photo.py
> +                                     tile=tileid, readonly=True, return_exists=True)
yes

2024-07-19 17:33 UTC, sbailey commented
> I'm not entirely sure what you're recommending here. Maybe you could express this as a code snippet?

Thinking about it more, let's just go all-in on making $FIBER_ASSIGN_DIR a required variable for standard operations, and not try to support an interim period where it might not be defined, since desimodules/main already defines it.

Heads up @sybenzvi, when you update desispec at KPNO, you'll also need to make sure that module files / config gets set to define FIBER_ASSIGN_DIR=$DESI_TARGET/fiberassign/tiles/trunk .

> However, I now realize that the way findfile is modified in this branch, an exception will be thrown if FIBER_ASSIGN_DIR is not defined anyway, and so maybe the solution is to catch a potential KeyError thrown by findfile, add a helpful message, and re-raise.

We're ok here.  You added
```python
if tiles_dir is None and 'tiles_dir' in required_inputs:
        tiles_dir = os.environ['FIBER_ASSIGN_DIR']
```
which means that $FIBER_ASSIGN_DIR is only required if tiles_dir is *not* specified, which is good.  We'll require $FIBER_ASSIGN_DIR for normal operations, but if for whatever reason someone is running without it, `findfile('fiberassignsvn', tiles_dir=...)` will work without requiring an envvar that it doesn't use (I explicitly checked that).

Summarizing, I think we want the `assemble_fibermap` block to be
```python
    if allow_svn_override:
        testfile, svn_exists = findfile('fiberassignsvn', tile=tileid, readonly=True, return_exists=True)
        if svn_exists:
            fafile = testfile
            log.info(f'Overriding raw fiberassign file {rawfafile} with svn {fafile}')
        else:
            log.info(f'{testfile}[.gz] not found; sticking with raw data fiberassign file')
```
i.e. findfile will require $FIBER_ASSIGN_DIR to exist and raise a KeyError if it doesn't, and this code handles the case where findfile works but the tile hasn't yet been committed to svn (svn_exists=False).

2024-07-19 17:44 UTC, weaverba137 commented on py/desispec/io/photo.py
> +                                     tile=tileid, readonly=True, return_exists=True)
OK, that also means that the argument to `desispec.io.photo.gather_targetdirs()` is now unused. Should I remove the argument?

2024-07-19 18:05 UTC, sbailey commented on py/desispec/io/photo.py
> +                                     tile=tileid, readonly=True, return_exists=True)
Sorry, I had missed that it is also an input argument, not just a temporary variable constructed from environment variables.  Updated suggestion: just use
```
fiberfile, svn_exists = findfile('fiberassignsvn', tiles_dir=fiberassign_dir,
                                     tile=tileid, readonly=True, return_exists=True)
```
without any pre-wrangling of `fiberassign_dir`.  If the input is `None`, then findfile will get it from $FIBER_ASSIGN_DIR, and if the input is not None, then findfile will use that.  No need for `gather_targetdirs` to do its own manipulation of `if fiberassign_dir is None`.

If that doesn't make sense, ping me on Slack and let's hop on zoom to sort this out in realtime.

2024-07-19 18:05 UTC, weaverba137 commented
@sbailey, I've made the requested changes, except for the open question about `io.photo` above.

2024-07-19 18:06 UTC, weaverba137 commented on py/desispec/io/photo.py
> +                                     tile=tileid, readonly=True, return_exists=True)
Thanx, we cross posted about this, but this is a good suggestion.

2024-07-19 18:07 UTC, weaverba137 commented on py/desispec/io/photo.py
> +                                     tile=tileid, readonly=True, return_exists=True)
The most recent commit should have all the requested changes in now.

2024-07-19 18:46 UTC, sbailey approved these changes
Looks good!  Thanks for iterating on all the details.

2024-07-19 18:46 UTC, merged

2024-07-19 18:53 UTC, sbailey commented
For the record: I have installed this updated version at NERSC